/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.leetcode.problem1625.Solution1625;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Solution1625.runProblem();
    }
}
