/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.leetcode.problem3397.Solution3397;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Solution3397.runProblem();
    }
}
