/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.leetcode.problem1.Solution1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Solution1 solution1 = new Solution1();
        solution1.solve();
    }
}
